<template>
  <n-config-provider>
    <n-notification-provider>
      <n-message-provider>
        <router-view></router-view>
      </n-message-provider>
    </n-notification-provider>
  </n-config-provider>
</template>
